language: node_js
node_js:
  # TODO: Restore the pipeline for latest Node.js when Travis fixes their
  # pipeline dependency problems. See #39
  # - "node" # Latest node version
  - "lts/*" # Latest LTS version
  - "14"
  - "12"

before_install: npm i -g npm@6.14.12

script:
   - commitlint-travis
   - npm run standards
   - npm run test
